apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
  namespace: grafana
spec:
  secretName: grafana-tls
  dnsNames:
  - grafana.seagull.ryusa.net
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
