---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafana
  labels:
    team: system
  namespace: prometheus
spec:
  endpoints:
  - interval: 1m
    scrapeTimeout: 30s
    honorLabels: true
    port: service
    path: /metrics
    scheme: http
  jobLabel: "grafana"
  selector:
    matchLabels:
        app.kubernetes.io/name: grafana
        app.kubernetes.io/instance: grafana
  namespaceSelector:
    matchNames:
      - grafana
