---
# Source: prometheus-node-exporter/templates/psp-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: psp-node-exporter-prometheus-node-exporter
  labels:     
    app: prometheus-node-exporter
    heritage: Helm
    release: node-exporter
    chart: prometheus-node-exporter-2.2.0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp-node-exporter-prometheus-node-exporter
subjects:
  - kind: ServiceAccount
    name: node-exporter-prometheus-node-exporter
    namespace: prometheus-node-exporter
