---
# Source: prometheus-node-exporter/templates/psp-clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp-node-exporter-prometheus-node-exporter
  labels:     
    app: prometheus-node-exporter
    heritage: Helm
    release: node-exporter
    chart: prometheus-node-exporter-2.2.0
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - node-exporter-prometheus-node-exporter
