apiVersion: v1
kind: Namespace
metadata:
  name: nfs-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nfs-server
  labels:
    app: nfs-server
  name: nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: kingfisher01
      containers:
      - image: itsthenetwork/nfs-server-alpine:12
        name: nfs-server
        ports:
        - name: nfs
          containerPort: 2049
        env:
          - name: SHARED_DIRECTORY
            value: /exports
        securityContext:
          privileged: true
        volumeMounts:
        - name: exports
          mountPath: /exports
      volumes:
      - name: exports
        hostPath: 
          path: /data/exports
---
apiVersion: v1
kind: Service
metadata:
  namespace: nfs-server
  annotations:
    external-dns.alpha.kubernetes.io/hostname: nfs.seagull.ryusa.net
  labels:
    app: nfs-server
  name: nfs-server
spec:
  ports:
  - name: nfs
    port: 2049
    protocol: TCP
    targetPort: nfs
  selector:
    app: nfs-server
  type: LoadBalancer
