---
# Source: argo-cd/templates/argocd-application-controller/metrics-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    helm.sh/chart: argo-cd-3.26.5
    app.kubernetes.io/name: argocd-metrics
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/component: application-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
  name: argocd-application-controller-metrics
spec:
  ports:
  - name: metrics
    protocol: TCP
    port: 8082
    targetPort: controller
  selector:
    app.kubernetes.io/name: argocd-application-controller
    app.kubernetes.io/instance: argocd
