---
# Source: metallb/templates/psp.yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: metallb-controller
  labels:
    helm.sh/chart: metallb-0.11.0
    app.kubernetes.io/name: metallb
    app.kubernetes.io/instance: metallb
    app.kubernetes.io/version: "v0.11.0"
    app.kubernetes.io/managed-by: Helm
spec:
  privileged: false
  # Host namespaces
  hostPID: false
  hostIPC: false
  hostNetwork: false
  # Volumes and file systems
  volumes:
  - configMap
  - secret
  - emptyDir
  allowedHostPaths: []
  readOnlyRootFilesystem: true
  # Users and groups
  runAsUser:
    rule: MustRunAsNonRoot
  supplementalGroups:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65535
  fsGroup:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65535
  # Privilege Escalation
  allowPrivilegeEscalation: false
  defaultAllowPrivilegeEscalation: false
  # Capabilities
  allowedCapabilities: []
  defaultAddCapabilities: []
  requiredDropCapabilities:
  - ALL
  # SELinux
  seLinux:
    rule: RunAsAny
---
# Source: metallb/templates/psp.yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: metallb-speaker
  labels:
    helm.sh/chart: metallb-0.11.0
    app.kubernetes.io/name: metallb
    app.kubernetes.io/instance: metallb
    app.kubernetes.io/version: "v0.11.0"
    app.kubernetes.io/managed-by: Helm
spec:
  privileged: true
  # Host namespaces
  hostPID: false
  hostIPC: false
  hostNetwork: true
  hostPorts:
  - min: 7472
    max: 7472
  - max: 7946
    min: 7946
  # Volumes and file systems
  volumes:
  - configMap
  - secret
  - emptyDir
  allowedHostPaths: []
  readOnlyRootFilesystem: true
  # Users and groups
  runAsUser:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  # Privilege Escalation
  allowPrivilegeEscalation: false
  defaultAllowPrivilegeEscalation: false
  # Capabilities
  allowedCapabilities:
  - NET_RAW
  defaultAddCapabilities: []
  requiredDropCapabilities:
  - ALL
  # SELinux
  seLinux:
    rule: RunAsAny
