---
# Source: metallb/templates/service-accounts.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metallb-controller
  labels:
    helm.sh/chart: metallb-0.11.0
    app.kubernetes.io/name: metallb
    app.kubernetes.io/instance: metallb
    app.kubernetes.io/version: "v0.11.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
---
# Source: metallb/templates/service-accounts.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metallb-speaker
  labels:
    helm.sh/chart: metallb-0.11.0
    app.kubernetes.io/name: metallb
    app.kubernetes.io/instance: metallb
    app.kubernetes.io/version: "v0.11.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: speaker
