---
# Source: vcluster/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vc-speedtest-cluster
  namespace: speedtest-cluster
  labels:
    app: vcluster
    chart: "vcluster-0.4.3"
    release: "speedtest-cluster"
    heritage: "Helm"
