---
# Source: sealed-secrets/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sealed-secret-sealed-secrets-key-admin
  namespace: sealed-secrets
  labels:
    app.kubernetes.io/name: sealed-secrets
    helm.sh/chart: sealed-secrets-1.16.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: sealed-secret
    app.kubernetes.io/version: v0.16.0
rules:
  - apiGroups:
      - ""
    resourceNames:
      - sealed-secrets-key
    resources:
      - secrets
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - list
---
# Source: sealed-secrets/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sealed-secret-sealed-secrets-service-proxier
  namespace: sealed-secrets
  labels:
    app.kubernetes.io/name: sealed-secrets
    helm.sh/chart: sealed-secrets-1.16.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: sealed-secret
    app.kubernetes.io/version: v0.16.0
rules:
- apiGroups:
  - ""
  resourceNames:
  - 'http:sealed-secret-sealed-secrets:'
  - sealed-secret-sealed-secrets
  resources:
  - services/proxy
  verbs:
  - create
  - get
