apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/in-cluster/grafana
    repoURL: https://github.com/ryusa/seagull-project.git
    targetRevision: HEAD
    directory:
      recurse: true
      exclude: templates/tests/*
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
