apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://w349ytr.seagull.ryusa.net
  project: default
  source:
    path: manifests/in-cluster/nginx
    repoURL: https://github.com/ryusa/seagull-project.git
    targetRevision: HEAD
    directory:
      recurse: true    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
