apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets
---
apiVersion: v1
kind: Secret
metadata:
  name: sealed-secrets-key
  namespace: sealed-secrets
  labels:
    sealedsecrets.bitnami.com/sealed-secrets-key: active
type: kubernetes.io/tls
data:
  tls.crt: XXX
  tls.key: XXX
