---
# Source: external-dns/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external-dns
  namespace: prometheus
  labels:
    team: system
spec:
  jobLabel: external-dns
  namespaceSelector:
    matchNames:
      - external-dns
  selector:
    matchLabels:
      app.kubernetes.io/name: external-dns
      app.kubernetes.io/instance: external-dns
  endpoints:
    - port: http
      path: /metrics
      interval: 1m
      scrapeTimeout: 10s
