---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: system-prometheus
  namespace: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: system
  podMonitorSelector:
    matchLabels:
      team: system
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 40Gi
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
