---
# Source: prometheus-pushgateway/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: speedtest-pushgateway
  labels:
    app: prometheus-pushgateway
    chart: prometheus-pushgateway-1.13.0
    heritage: Helm
    release: speedtest
