---
# Source: vcluster/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vc-dev-cluster
  namespace: dev-cluster
  labels:
    app: vcluster
    chart: "vcluster-0.4.3"
    release: "dev-cluster"
    heritage: "Helm"
